spring:
  application:
    name: ms-cartoes

  profiles:
    active: dev

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

mq:
  exchange: cartoes.ex
  queues:
    emissao-cartoes: emissao-cartoes

rabbitmq:
  exchange:
    cliente: cliente.exchange
  queue:
    cliente-criado: cliente.criado.ms-cartoes.queue
  routing-key:
    cliente-criado: cliente.criado.rk

server:
  port: 0

  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: false
    include-exception: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  health:
    readinessstate:
      enabled: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin-eureka-user:admin-eureka-password@localhost:8761/eureka/
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    health-check-url-path: /actuator/health